<a href="https://colab.research.google.com/github/snowfiap/Python-Basics/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BASICS OF NUMPY

In [ ]:
import numpy as np

### Creating 1D array

In [ ]:
a1=np.array([1,2,3,4,5])
a1


In [ ]:
a2=np.array([10,20,30,40,50])
a2

In [ ]:
#Can access the elements of array just like a list
a1[3]

In [ ]:
a2[0]

In [ ]:
#Can also check the dimension of the array
a1.ndim

In [ ]:
#adding two arrays
a1+a2

In [ ]:
#Subtracting two  arrays
a2-a1

In [ ]:
#multiplying two arrays
a1*a2

In [ ]:
#Finding square of array1
a1**2

In [ ]:
#Finding square of array2
a2**2

## Creating 2D Array

In [ ]:
a3=np.array([[1,2,3,],[4,5,6],[7,8,9]])
a3

In [ ]:
#checking the dimension of the array
a3.ndim

## Itemsize property

In [ ]:
#It shows the size of each item stored
a3.itemsize #since the entries  are integers it has 4 bytes

In [ ]:
a3.dtype

In [ ]:
#changing the array from integer to float in order to check the ittemsize
a3=np.array([[1,2,3,],[4,5,6],[7,8,9]],dtype=np.float64)
a3

In [ ]:
#Since it is changed tofloat it will return 8 bytes
a3.itemsize

In [ ]:
#finding no.of elements in an array
a3.size

In [ ]:
#Finding the shape of the array(No.of rows and columns)
a3.shape 

In [ ]:
#Checking the datatype
a3.dtype


In [ ]:
#changing the array from integer to complex 
a3=np.array([[1,2,3,],[4,5,6],[7,8,9]],dtype=complex)
a3

In [ ]:
#printing zero's array
a4=np.zeros((3,2))
a4

In [ ]:
#printing one's array
a5=np.ones((4,5))
a5

## Using rangeof function

In [ ]:
x=range(5)
x

In [ ]:
x[3]

In [ ]:
y=np.arange(90,100)
y

In [ ]:
#Retrieving elements of the array
y[3]

In [ ]:
#printing numbers in a particular range
z=np.arange(1,30,5)

## Using Linspace to print n numbers 

In [ ]:
#It prints 10 linearly spaced numbers between 1 to 5
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

## Reshaping the Array

In [ ]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#reshaping
arr1.reshape(2,6) #2 rows and 6 columns

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
#reshaping
arr1.reshape(6,2) #6 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

## Flattening the Array-Converting the 3D,2D Arrays to 1D Array

In [ ]:
arr1.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr2=np.arange(20).reshape(4,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr2.ravel()#flattening

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Finding Minimum,Maximum elements in the array

In [ ]:
arr1.min()


1

In [ ]:
arr1.max()

12

In [ ]:
arr2.min()

0

In [ ]:
arr2.max()

19

## Finding the Sum of Array

In [ ]:
arr1.sum()

78

In [ ]:
#Sum can be calculated based on axis (0 indicates columns and 1 indicates rows)
arr1.sum(axis=0)

array([22, 26, 30])

In [ ]:
arr2.sum(axis=1)

array([10, 35, 60, 85])

## Finding Square Root of the Array

In [ ]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [ ]:
np.sqrt(arr2)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894]])

## Finding the Standard Deviation of the Array

In [ ]:
np.std(arr1)

3.452052529534663

In [ ]:
np.std(arr2)

5.766281297335398

## Peforming Matrix Product

In [ ]:
arr3=np.arange(11,17).reshape(3,2)
arr3

array([[11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
arr1.dot(arr3) # To perform matrix multiplication dimension should satisfy the condition i.e No.of columns is 1 array should match with No.of rows in 2 array


array([[ 82,  88],
       [199, 214],
       [316, 340],
       [433, 466]])

## Indexing and Slicing of the Array

In [ ]:
arr3[1] #prints the 2 row

array([13, 14])

In [ ]:
arr1[-1] # Prints the last row of arr1


array([10, 11, 12])

In [ ]:
#Slicing
arr3[0:2]

array([[11, 12],
       [13, 14]])

In [ ]:
arr2[1:4]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr1[1,2]#Prints the element in 1 row and 2 column

6

In [ ]:
arr2[0:2,2] #Prints element in  0 and 1  row and which is in 2 column

array([2, 7])

## Iterating through the Array


In [ ]:
for row in arr3:
  print(row)

[11 12]
[13 14]
[15 16]


In [ ]:
#flattening the array
for cell in arr1.flat:
  print(cell)


1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#Splitting the array
arr4=np.arange(50)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
#Horizontal Split
result=np.hsplit(arr4,5)
result

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]),
 array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])]

In [ ]:
arr5=np.arange(50)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
result1=np.hsplit(arr5,10)
result

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]),
 array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])]

#3 Stacking of Array

In [ ]:
arr6=np.arange(21,33).reshape(4,3)
arr6

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])

In [ ]:
#Horizontal Stacking
np.vstack((arr1,arr6))#Stacking can be implemented only when the dimensions are exactly same

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])

In [ ]:
#Vertical Stacking
np.hstack((arr1,arr6))

array([[ 1,  2,  3, 21, 22, 23],
       [ 4,  5,  6, 24, 25, 26],
       [ 7,  8,  9, 27, 28, 29],
       [10, 11, 12, 30, 31, 32]])

## Indexing with Boolean arrays

In [ ]:
arr3

array([[11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
cond=arr6>25
cond# It prints a Boolean Array

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
arr6[cond] #It returns the value which is greater than 25 in the array

array([26, 27, 28, 29, 30, 31, 32])

In [ ]:
#Can also replace the value of those elements in the array
arr6[cond]=0
arr6

array([[21, 22, 23],
       [24, 25,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]])